- README.md
- package.json
- src/index.js
This PR creates an index.js to establish a top level, public API for the library. It also updates the example to use the npm library.
Open to exporting other stuff in the public API. I'm not yet sure what is meant to be exposed and what isn't.
> **Note**: I bumped the version to 0.2.0 and you'll need to publish it
for the README example to work.
> feat: Expose public top-level API

- .github/workflows/release.yml
This should publish the NPM package when a GitHub release is created. You'll need to get a token from NPM: https://docs.npmjs.com/creating-and-viewing-access-tokens
Set it to `NPM_TOKEN` in your action secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository
> feat: Publish to NPM when a release is created

- .npmignore
- package-lock.json
- package.json
Seems our ESM based library prefer this and gets confused by main. Still seems to work for CJS builds too. Our library builds both CJS and ESM modules.
> fix: ESM projects prefer "exports"

- src/fs_fd.js
Honestly, I don't really like this 'fix'. There's several style problems and no real consistency. But:
I've initialized `stdin`/`stdout` to point to open files. Then an instace of [rust WASI example](https://github.com/wapm-packages/rust-wasi-example) compiled with wasm32-wasi (Rust 1.65) will try to print to stdout, repeating `Hello, world!` three times.
This crashed in the file operations, in particular during some initial seek, which passes its offset as `i64`(wasm)/`BigInt`(js). The fix is currently to consistently use a 64-bit type for the internal representation of the offset but the checks are missing. This PR is to raise some awareness and remind me to contribute a proper fix.
```rust
import { WASI, File, PreopenDirectory } from "@bjorn3/browser_wasi_shim";
async function …
```
> Fix file_pos used as both Number and BigInt arithmetic

- package.json
- src/fs_core.js
- src/fs_fd.js
- src/index.js
- src/wasi.js
CommonJS style exports were previously used in index.js despite being an ESM module. Switching to the ESM export syntax fixes webpack.
Fixes #12
> Fix webpack when using browser_wasi_shim as dependency

- src/index.ts
Follow-up to #18, importing without `.js` is causing the module resolution to fail in some cases.
> Fix file imports

- src/index.ts
We need to export `Fd` to be able to import it from the package. The export for `OpenDirectory` was also missing.
Apologies for opening yet another PR 😅
> Add missing export for Fd

- package.json
This is needed so typescript can find the `d.ts`, given it's not next to the `.js`.
> Fix types of export map

- src/wasi.ts
Outside of browsers it will fallback to returning 0 like was previously done unconditionally.
Fixes #23
> Use performance.now() to implement CLOCKID_MONOTONIC in browsers

- package-lock.json
- package.json
- src/fd.ts
- src/fs_fd.ts
- src/wasi.ts
- src/wasi_defs.ts
The field `{offset}` returned from `OpenFile::fd_seek` can be promoted to BigInt. Later on, in `WASI::fd_seek` the call to `buffer.setInt32` fails for BigInt. The proposed patch fixes the problem.
> BigInt offset typings 

- .gitignore
- examples/rustc.html
- src/fd.ts
- src/fs_core.ts
- src/fs_fd.ts
- src/strace.ts
- src/wasi.ts
- src/wasi_defs.ts
You can download the precompiled rustc binary from https://github.com/rust-lang/miri/issues/722#issuecomment-1584287506. You will need to unpack the contained `dist` directory as `examples/wasm-rustc`.
> Fix rustc example

- src/fd.ts
- src/fs_fd.ts
First of all, a huge thanks for creating this project. I have been using this for about a month with a few additions in a fairly large project (at work) and its been great. After the last few commits, only the remaining two changes are necessary to make it work. 
The `fd_sync` one is trivial. For `fd_seek` on directories, IIUC the return value is supposed to be treated as an opaque value so I return 0 there.
> Shim fd_sync

- src/fs_core.ts
- src/fs_fd.ts
* Handle `.` components in paths.
* Return EEXIST on non-existent files in path_filestat_get.
The first fix is required to run esbuild compiled to wasm: https://fosstodon.org/@jakebailey/110182326132563028 The second one improves error messages presented by guest programs.
> Misc fixes

- src/fs_core.ts
- src/fs_fd.ts
- src/index.ts
- src/wasi.ts
This could partly fix #32 by allowing to use [`FileSystemSyncAccessHandle`s](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSyncAccessHandle) in Workers for single files opened from [OPFS](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#origin_private_file_system) as [noted in my last comment](https://github.com/bjorn3/browser_wasi_shim/issues/32#issuecomment-1612637810). Usage example:
```ts
// open synchronous handle to a file in opfs
const opfs = await navigator.storage.getDirectory();
const file = await opfs.getFileHandle("example.txt");
const handle = await file.createSyncAccessHandle();
// populate the virtual filesystem for shim
const fds: Array<Fd> = [
new OpenFile(new File([])), // stdin
new OpenFile(new File([])), // stdout
new OpenFile(new …
```
> Add support for files in OPFS

- src/fs_core.ts
- src/fs_fd.ts
This PR adds an `options?: FileOptions` argument to `File` and `SyncOPFSFile`, where the only known option so far is a `readonly` boolean. This is then handled in `truncate()`, `fd_write()` and `path_open()`.
A usage example might be safely sharing a data file amongst multiple instances—or even Workers—by backing a `File` with a `SharedArrayBuffer` and marking it "readonly".
> Add readonly flag to Files

- src/wasi.ts
It just needs to *exist* in the imports for some binaries, even if they don't actually use it. For example the [Python interpreter](https://github.com/vmware-labs/webassembly-language-runtimes/releases/tag/python%2F3.11.4%2B20230714-11be424) requires this.
See #37 for more context.
> shim sock_accept

- src/fs_fd.ts
Hello again! ☺️ 
I was trying to get [a Python interpreter](https://github.com/vmware-labs/webassembly-language-runtimes/releases/tag/python%2F3.11.4%2B20230714-11be424) to run in the WASI shim and got weird errors like this:
```
Exception ignored error evaluating path:
Traceback (most recent call last):
File "<frozen getpath>", line 353, in <module>
OSError: [Errno 65535] Success
Fatal Python error: error evaluating path
Python runtime state: core initialized
Current thread 0x00000000 (most recent call first):
<no Python frame>
```
After enabling `strace` and uncommenting the `console.log` line, which prints the `path`, I found that the interpreter was trying to open `pyvenv.cfg` and `pybuilddir.txt`. Including those in the shimmed filesystem (even as empty files) allowed the interpreter …
> return proper ERRNOs in OpenDirectory.path_open

- .eslintrc.cjs
- .gitignore
- .gitmodules
- .prettierrc
- README.md
- examples/rustc.html
- package-lock.json
- package.json
- src/debug.ts
- src/fd.ts
- src/fs_core.ts
- src/fs_fd.ts
- src/index.ts
- src/strace.ts
- src/wasi.ts
- src/wasi_defs.ts
Thank you for this project @bjorn3!
This PR looks like a lot but has mostly cosmetic changes and is broken down into three commits:
- Formatting:
-  Formatted code with `prettier`
- Added .prettierrc configuration to prefer double quotes over single.
- Added formatting validation to the `check` task
- Linting/types
- Added eslint and recommended TypeScript lints
- Fixed lint errors (mostly let vs. const and unused variables)
- Fixed issues where TypeScript typings were being ignored.
- Added eslint to the `check` task
- README/Demo:
- Found the [wasm-rustc](https://github.com/rust-lang/miri/issues/722#issuecomment-1584287506) tarball and archived the contents [here](https://github.com/jsoverson/wasm-rustc). I can transfer that repo to you as it makes more sense here.
- Added that repo as …
> Made project more accessible to contributions

- src/fs_fd.ts
> fix: bug where os.Stat on a non-existent file would return "File exists" error

- src/fs_fd.ts
> feat: implement fd_pread (similar to fd_read)

- src/fs_fd.ts
> fix: error code from path_open is not correct when trying to open a non-directory as a directory

- src/fs_core.ts
- src/fs_fd.ts
Fixes #49 
This adds support for the path_remove_directory and path_unlink_file system calls.
> feat: implement path_remove_directory and path_unlink_file system calls

- src/fd.ts
Negative errno value is not expected at least by wasi-libc and `strerror(-1)` returns "Success" as an undefined behavior. To avoid such confusion, it might be better to return `ENOTSUP` for unimplemented syscalls instead of invalid errno -1.
This change makes `browser_wasi_shim` work with ruby.wasm.
```console
$ cat main.c
#include <stdio.h>
#include <string.h>
int main(void) {
printf("%s\n", strerror(-1));
return 0;
}
$ $WASI_SDK_PATH/bin/clang main.c
$ wasmtime a.out
Success
```
> fix: return ENOTSUP instead of -1 for unsupported syscalls

- .github/workflows/check.yml
- .gitmodules
- README.md
- package.json
- test/adapter.py
- test/run-testsuite.sh
- test/run-wasi.mjs
- test/skip.json
Based on https://github.com/bjorn3/browser_wasi_shim/pull/57
> test: Setup wasi-testsuite with Node.js adapter

- src/wasi.ts
This behavior is consistent with Node.js's `WASI.start()`. https://github.com/nodejs/node/blob/v21.4.0/lib/wasi.js#L117
> fix: Return 0 from `WASI.start()` on success

- examples/rustc.html
- src/fd.ts
- src/fs_core.ts
- src/wasi.ts
There are part of the failures with typescript strict mode.
> Introduce type hints in a couple more places

- package.json
This should allow importing it using old style CJS include()
Fixes #64
> Add default export

- README.md
- src/fs_core.ts
- src/index.ts
- test/adapters/browser/run-test.html
Closes #66
Also used it in the example in the README for better discoverability, but can also remove the commit from the PR ofc.
> Add `ConsoleStdout`

- src/wasi.ts
The `_initialize` export is optional and may not exist in a wasi reactor module, according to https://github.com/WebAssembly/WASI/blob/main/legacy/application-abi.md#current-unstable-abi. When it doesn't exist, simply don't do anything. This is especially useful in cases where a module has been pre-initialized by `wizer` and the `_initialize` export has been stripped.
> Handle `_initialize` non existence in wasi reactor modules

- src/index.ts
So you can do
```js
try {
instance.exports.my_exported_func();
return 0;
} catch (e) {
if (e instanceof WASIProcExit) {
return e.code;
} else {
throw e;
}
}
```
> fix: reexport the WASIProcExit error so it can be caught when calling exported functions

- src/wasi.ts
I simply modified the `random_get` implementation to use `crypto.getRandomValues` to generate the random numbers.
This has the benefit that the RNG is cryptographically secure, and is probably faster that the previous implementation (though that should be benchmarked).
> Modify random_get to use crypto.getRandomValues

- src/wasi.ts
Related issue: https://github.com/w3c/webcrypto/issues/213
In chrome, Crypto doesn't work with SharedArrayBuffer. it makes error `The provided ArrayBufferView value must not be shared.`.
I suggest to use previous Math random code when memory is SharedArrayBuffer.
> Prevent using crypto for SharedArrayBuffer

- package.json
Some of bundler tools like Parcel do not support the "exports" field yet. This change defines the top-level "main" and "types" fields in package.json as a fallback.
> Define top-level "main" and "types" fields in package.json

- src/fd.ts
- src/fs_mem.ts
- src/fs_opfs.ts
- src/wasi_defs.ts
- test/adapters/node/run-wasi.mjs
- threads/src/shared_array_buffer/ref.ts
Some applications rely on the ino's uniqueness to identify a file. For example, musl-fts uses ino to detect a cycle in the directory tree, and it now wrongly detects a cycle with this WASI impl because the ino is always 0. This change makes the ino unique for each node.
> Return unique ino for each node for `Filestat` and `Dirent`

- src/wasi.ts
My WASI programs were crashing when Unicode was used in environment variables. Saw that it was a quick fix. While `environ_get` properly encodes the string, `environ_sizes_get` doesn't when determining length.
> quick fix for unicode in environment variables
